/**
 * useFileSystem
 *
 * Adapter hook that normalises file I/O across two environments:
 *
 *  Desktop (Tauri)
 *    → invoke('import_atlas_hcl')
 *      Opens a native file-picker, reads the .hcl file in Rust, parses it
 *      with core::parse_atlas_hcl, and returns a Diagram JSON string.
 *
 *  Web (Wasm / Cloudflare Pages)
 *    → <input type="file"> + wasm import_hcl()
 *      Opens a browser file-picker, reads the file as text in JS, passes it
 *      to the compiled Wasm function, and returns a Diagram JSON string.
 */

import { useCallback } from "react";
import { useDiagramStore, type CoreDiagram } from "../store/useDiagramStore";

// ---------------------------------------------------------------------------
// Environment detection
// ---------------------------------------------------------------------------

/** True when running inside a Tauri desktop app */
function isTauri(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

// ---------------------------------------------------------------------------
// Lazy Wasm loader
// ---------------------------------------------------------------------------

// The Wasm module is only bundled / loaded when actually needed (Web path).
// We use a dynamic import so Vite can tree-shake it from the Tauri build.
let wasmImportHcl: ((hcl_str: string) => string) | null = null;

async function getWasmImportHcl(): Promise<(hcl_str: string) => string> {
  if (wasmImportHcl) return wasmImportHcl;
  // Wasm package is generated by `wasm-pack build --target web` in core/.
  // The dynamic import is intentionally untyped until the pkg/ directory
  // is generated; the cast below is safe because wasm-bindgen guarantees
  // the export signature matches.
  const wasmPath = "../../core/pkg/er_diagram_core.js";
  // `/* @vite-ignore */` suppresses "cannot resolve" at build time because
  // pkg/ is generated by `wasm-pack build` and does not exist in source.
  const wasm = await import(/* @vite-ignore */ wasmPath) as {
    default: () => Promise<void>;
    import_hcl: (hcl_str: string) => string;
  };
  await wasm.default(); // initialise wasm
  wasmImportHcl = wasm.import_hcl;
  return wasm.import_hcl;
}

// ---------------------------------------------------------------------------
// File picker helpers
// ---------------------------------------------------------------------------

/** Open a native Tauri file-picker and return the parsed Diagram JSON. */
async function importViaIpc(): Promise<string> {
  const { invoke } = await import("@tauri-apps/api/core");
  return invoke<string>("import_atlas_hcl");
}

/** Open a browser <input type="file"> and return the parsed Diagram JSON. */
async function importViaFilePicker(): Promise<string> {
  const text = await pickFileAsText(".hcl");
  const importHcl = await getWasmImportHcl();
  return importHcl(text);
}

function pickFileAsText(accept: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = accept;
    input.onchange = () => {
      const file = input.files?.[0];
      if (!file) { reject(new Error("No file selected")); return; }
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => reject(new Error("Failed to read file"));
      reader.readAsText(file);
    };
    input.oncancel = () => reject(new Error("Cancelled"));
    input.click();
  });
}

// ---------------------------------------------------------------------------
// Hook
// ---------------------------------------------------------------------------

export function useFileSystem() {
  const importFromCore = useDiagramStore((s) => s.importFromCore);

  const importHcl = useCallback(async () => {
    try {
      const json = isTauri()
        ? await importViaIpc()
        : await importViaFilePicker();

      const diagram: CoreDiagram = JSON.parse(json);
      importFromCore(diagram);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      if (msg !== "No file selected" && msg !== "Cancelled") {
        console.error("[useFileSystem] importHcl failed:", msg);
        alert(`インポートエラー: ${msg}`);
      }
    }
  }, [importFromCore]);

  return { importHcl };
}
